url: "https://kobethuwis.github.io/"

defaults:
  -
    scope:
      path:            "assets/download/Thuwis_Kobe_CV.pdf"
    values:
      sitemap:         false
      noindex:         true
      
plugins:
  - jekyll-sitemap
