title: Kobe Thuwis - Creative developer
email: kobethuwis26@gmail.com
description: A youthful AI engineer, researcher and robotics developer. Take a look at my personal portfolio of previous projects, experience and skills!
baseurl: ""
favicon: /favicon.ico
url: "https://kobethuwis.github.io/"
   
github_username: kobethuwis
      
plugins:
  - jekyll-sitemap
