title: Kobe Thuwis
email: kobethuwis26@gmail.com
description: Creative developer, specialised in AI & robotics.

baseurl: ""
url: "https://kobethuwis.github.io/"
   
github_username: kobethuwis

url: "https://kobethuwis.github.io/"
      
plugins:
  - jekyll-sitemap
